name: 'paysim_transformation'
version: '1.0.0'
config-version: 2

profile: 'paysim_transformation'

models:
  paysim_transformation:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    mart:
      +materialized: table